config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :users
  resources :tasks
  resources :habits

  root 'welcome#index'

  match 'complete_daily_habit' => 'habits#complete_daily_habit', :via => :post

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => "sessions#destroy"

  get '/signup' => "users#new"
  post '/users' => "users#create"

end

app/models/habit.rb
class Habit < ActiveRecord::Base

  belongs_to :user
  has_many :tasks
  has_one :icon

  validates_presence_of :name
#  validates_presence_of :description
  validates_presence_of :start_date
  validates_presence_of :end_date
  validates_presence_of :user_id

  def completed_days
    tasks.where(completed: true).count || 0
  end

  def incomplete_days
    tasks.where("completed = ? AND task_date < ?", false, Date.today).count || 0
  end

  def total_days_in
    completed_days + incomplete_days
  end

  def completion_average
    ((completed_days.to_f / (total_days_in.to_f + 1) ) * 100).round
  end

  def days_remaining
    30 - completed_days - incomplete_days
  end

  def task_for_today
    tasks.where(completed: false, task_date: Date.today).first
  end

  def self.active_habits
    Habit.where(active: true)
  end

  def create_task_for_habit
    puts "successful run of scheduler"
  end

  def longest_running_streak
    #TODO
    #figure out how to do this.
  end

  def icon_path
    Icon.find(self.habit_type).icon_path
  end

  # Scheduler Methods
  def self.create_daily_tasks
    active_habits.each do |habit|
      Task.create(
        habit_id: habit.id,
        completed: false,
        task_date: Date.today)

    end
  end

  def self.expire_old_habits
    habits = Habit.all
    habits.all.each do |habit|
      date_range = habit.start_date..habit.end_date
      if date_range === Date.today
        Rails.logger.info "active"
        puts "nothing to see here"
      else
        habit.update_attributes(active: false)
      end
    end
  end

end

app/models/icon.rb
class Icon < ActiveRecord::Base
  belongs_to :habit

  MIND = 1
  BODY = 2
  SOUL = 3
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :habit

  validates_presence_of :habit_id
  validates_presence_of :task_date
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :password
  validates_presence_of :password_confirmation

  has_many :habits

  def active_habits
    habits.where(active: true)
  end

  def incomplete_daily_habit
    # active habit where the daily task isn't completed.
    habits_todo = []
    active_habits.each do |habit|
      if habit.tasks.where(completed: false, task_date: Date.today).present?
        habits_todo << habit
      end
    end
    habits_todo
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_filter :authorize

  def index
    @habits = Habits.all
  end

  def show
    @habit = Habit.find(params[:id])
  end

  def new
    @habit = Habit.new
    @habits = Habit.all
  end

  def create
    @habit = Habit.new(habit_params)

    if @habit.save
      Task.create(
        habit_id: @habit.id,
        completed: false,
        task_date: Date.today)

      redirect_to root_path
      flash[:success] = "Habit Created!"
    else
      flash[:error] = "Whoops something went wrong!"
      redirect_to root_path
    end
  end

  def destroy
    @habit = Habit.find(params[:id])
    @habit.destroy

    redirect_to root_path
  end

  def complete_daily_habit
    @habit = Habit.find_by(id: params[:completed_habit_id])
    @task = @habit.task_for_today
    @task.update_attributes(completed: true)
    respond_to do |format|
      format.json { head :ok }
    end
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :description, :habit_type, :start_date, :end_date, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/'
      flash[:error] = "Error logging in!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task =Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task
    else
      render 'new'
    end
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:habit_id, :completed, :task_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
     @user = User.find(params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/'
      flash[:error] = "Whoops, something went wrong!"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @habit = Habit.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    if flash_type == "error"
      return "alert-danger"
    else
      return "alert-success"
    end
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in text-center") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/habits/_form.html.erb
<%= form_for @habit do |f| %>

  <% if @habit.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@habit.errors.count, "error") %> prohibited
         this habit from being saved:
       </h2>
       <ul>
         <% @habit.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

     <!-- Text input-->
     <div class="form-group">
       <div class="col-md-2">
         <%= f.text_field :name,  :class =>"form-control input-md", :placeholder => "Habit Name" %>
       </div>
     </div>

     <!-- Text input-->
     <div class="form-group", style="padding-top: 5px;">
       <div class="col-md-2">
         Type:<%= f.select :habit_type, options_for_select([["Mind", 1], ["Body", 2 ], ["Soul", 3]], @habit.habit_type), class: "form-control input-md" %>
       </div>
     </div>

     <p hidden>
     <%= f.date_field :start_date, value: Date.today %>
     <%= f.date_field :end_date, value: (Date.today + 30.days) %>
     <%= f.number_field :user_id, value: current_user.id %>
     </p>

     <!-- Button -->
     <div class="form-group">
       <div id="create-habit-btn", class="col-md-1", style="margin-top: -15px">
         <%= f.submit %>
       </div>
     </div>

<% end %>

app/views/habits/edit.html.erb
<h1> Edit Habit </h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/habits/new.html.erb
<div class="container">
  <div class="span12">
    <%= render 'form' %>
  </div>
</div>

app/views/habits/show.html.erb
<p>
  <strong>Habit:</strong>
  <%= @habit.name%>
</p>

<p>
  <strong>Description:</strong>
  <%= @habit.description%>
</p>

<%= link_to 'Edit', edit_habit_path(@habit) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trickle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


    <nav class="navbar navbar-inverse">
      <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Trickle</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <div class="dropdown">
              <div class="navbar-brand" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <%= current_user.name %>
                <span class="caret"></span>
              </div>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><%= link_to "Logout", '/logout' %></li>
              </ul>
            </div>
          <% end %>
        </ul>
        <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse2">
          <form class="navbar-form navbar-right form-inline" role="form">
            <div class="form-group">
              <label class="sr-only" for="Email">Email</label>
              <input type="email" class="form-control" id="Email" placeholder="Email" autofocus required />
            </div>
            <div class="form-group">
              <label class="sr-only" for="Password">Password</label>
              <input type="password" class="form-control" id="Password" placeholder="Password" required />
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav><!-- /.navbar -->

  <%= flash_messages %>
  <%= yield %>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>

  <% if @task.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@task.errors.count, "error") %> prohibited
         this task from being saved:
       </h2>
       <ul>
         <% @task.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

   <p>
     <%= f.label :Completed? %><br>
     <%= f.check_box :completed %>
   </p>

   <p hidden>
     <%= f.hidden_field :habit_id, value: @task.habit_id%>
     <%= f.date_field :task_date, value: Date.today %>
   </p>

   <p>
     <%= f.submit %>
   </p>

<% end %>

app/views/tasks/edit.html.erb
<h1> Edit Task </h1>

<%= render 'form' %>

<%= link_to "Back", tasks_path %>

app/views/tasks/new.html.erb
<h1> New Tasks </h1>

<%= render 'form' %>

<%= link_to "Back", tasks_path %>

app/views/users/new.html.erb
<h1> Signup! </h1>

<%= form_for :user, url: '/users' do |f| %>
  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email%>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<h1> Users !!! </h1>

<p> Name: <%= current_user.name %>

app/views/welcome/_login_register_form.html.erb
<div class="col-md-4 col-xs-8 col-md-offset-2 col-xs-offset-2">
  <div class="panel panel-login">
    <div class="panel-heading">
      <div class="row">
        <div class="col-xs-6">
          <a href="#" class="active" id="login-form-link">Login</a>
        </div>
        <div class="col-xs-6">
          <a href="#" id="register-form-link">I'm New</a>
        </div>
      </div>
      <hr>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-12">
          <%= form_tag '/login',  id: "login-form", html: { style: "display: block;" } do %>
            <div class="form-group">
              <%= text_field_tag :email, nil, placeholder: "Email", class: "form-control", id: "username" %>
            </div>
            <div class="form-group">
              <%= password_field_tag :password, nil, placeholder: "Password", class: "form-control", id: "password" %>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                  <%= submit_tag "Log In", class: "form-control btn btn-login", id: "login-submit" %></p>
                </div>
              </div>
            </div>
          <% end %>

          <%= form_for :user, url: '/users',html: { id: "register-form", style: "display: none;" } do |f| %>
            <div class="form-group">
              <%= f.text_field :name, placeholder: "Name", class: "form-control", id: "username" %>
            </div>
            <div class="form-group">
              <%= f.text_field :email, placeholder: "Email Address", class: "form-control", id: "email" %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, placeholder: "Password", class: "form-control", id: "password" %>
            </div>
            <div class="form-group">
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control", id: "confirm-password" %>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                  <%= submit_tag "Let's Get Started", class: "form-control btn btn-register", id: "register-submit" %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_signed_in.html.erb
<section id="login">
  <div class="container">
    <div class="row">
    <p><div class="btn btn-lg btn-primary", id="add-client-btn", style="float: right; margin-bottom: 15px;">Create a new Habit Now!</div></li>
    <div id="habit-form", class="hidden">
      <%= render partial: "habits/form" %>
    </div>

      <div class="col-xs-12">
        <section class="jumbotron text-center">
          <div class="container-fluid">
            <div class="jumbotron">
              <h3>Did you complete Today's Habits?</h3>
              <% if current_user.incomplete_daily_habit.present? %>
                <% current_user.incomplete_daily_habit.each do |habit| %>
                  <div class="col-md-4 col-xs-4" style="padding-top: 20px;">
                    <div class="js-habit-<%= habit.id %>">
                      <i class="fa fa-<%= habit.icon_path %> fa-3x"></i><br />
                      <%= habit.name %> <br />
                        <div class="btn btn-primary js-complete-task" id="<%= habit.id %>"> Complete </div>
                    </div>
                  </div>
                <% end %>
              <% else%>
                <p> Good Job! You've completed all your habits for the day!  </p>
                <p> See you tomorrow.</p>
              <% end %>
            </div>
          </div>
        </section>

        <section class="jumbotron">
          <div class="container-fluid">
            <div class="jumbotron">
              <h3 class="text-center">DashBoard! </h3>
                <table class="table">
                  <tr>
                    <th>Name</th>
                    <th>Days Completed</th>
                    <th>Days Missed </th>
                    <th>Days Remaining</th>
                    <th>Trickle Percentage</th>
                    <th></th>
                  </tr>
                  <% current_user.active_habits.each do |habit| %>
                    <tr>
                      <td><%= habit.name %> </td>
                      <td><%= habit.completed_days %> </td>
                      <td><%= habit.incomplete_days %> </td>
                      <td><%= habit.days_remaining %> </td>
                      <td><%= habit.completion_average %>% </td>
                      <td> <%= link_to habit_path(habit.id), method: :delete do %>
                        <i class="fa fa-trash"></i>
                      <% end %>
                      </td>
                    </tr>
                  <% end %>
                </table>

            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_signed_out.html.erb
<div class="container-fluid jumbotron">

  <div class="col-md-5 text-center", style="padding-top: 50px;">
    <h1>Welcome To Trickle!</h1>
    <h3>Build Better habits in 30 days!</h3>
  </div>
  <%= render partial: "login_register_form" %>
</div>

app/views/welcome/index.html.erb
<% if current_user.present? %>
  <%= render partial: "signed_in" %>
<% else %>
  <%= render partial: "signed_out" %>
<% end %>